transpile: tests: rename `main.c` to `main_fn.c` since the `main.rs` generated is detected as a test
When testing `main.c`, `main.rs` is generated, and `cargo` thinks
`c2rust-transpile/tests/snapshots/main.rs` is a second `snapshots` test,
in addition to `c2rust-transpile/tests/snapshots.rs`:

```shell
❯ cargo test -p c2rust-transpile
error: failed to load manifest for workspace member `/home/kkysen/work/c2rust/c2rust`

Caused by:
  failed to load manifest for dependency `c2rust-transpile`

Caused by:
  failed to parse manifest at `/home/kkysen/work/c2rust/c2rust-transpile/Cargo.toml`

Caused by:
  found duplicate test name snapshots, but all test targets must have a unique name
```

This was from #1447, but wasn't caught in CI because it only runs `cargo test` a single time.