transpile: do not panic in `translate_failure` with `--fail-on-error`
it might seem like panicking here would speed up debugging, because it would provide a backtrace directly to something approximating the root cause of the translation failure.

sadly, this is not at all the case: `translate_failure` is only called from the top-level `translator::translate` function, which decides whether to call it based on whether the more interesting functions such as `convert_decl` and `convert_main` return `Err(_)`. by the time `translate_failure` runs, the interesting functions have returned and the only relevant info is in the error string that we print *before* panicking. as such, the backtraces always look like this:

thread 'main' panicked at 'Translation failed, see error above', c2rust-transpile/src/translator/mod.rs:486:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/core/src/panicking.rs:142:14
   2: c2rust_transpile::translator::translate
   3: c2rust_transpile::transpile_single
   4: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   5: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   6: c2rust_transpile::transpile
   7: c2rust_transpile::main

this does not bring joy. we should just exit(1) here.